#!/usr/bin/env bash
# package_coverage_check.sh — a shipped document must not point at a file the package omits.
#
# WHY (measured 2026-07-28): the npm tarball shipped CLAUDE.md, README, CATALOG and the knowledge/
# base while omitting much of what they instruct the reader to open — 35 distinct paths existed in
# the repo, were named by a shipped document, and were absent from the tarball. `CLAUDE.md` told
# consumers to run `templates/predelete_check.sh` before a destructive op; that file did not ship.
# A gate you are told to run and cannot run is worse than one you were never told about.
#
# This is the ANTI-REGROWTH instrument for that class. Closing the 35 once is worth little: the set
# regrows every time a doc gains a reference or files[] gains an entry. So the check is mechanical
# and the exceptions are ENUMERATED, never implicit.
#
# SOURCE-TREE ONLY. Inside an installed package the un-shipped files are legitimately absent and
# package.json's files[] may not even be present in a comparable form, so the check self-skips.
#
# Usage:  bash scripts/package_coverage_check.sh
# Exit:   0 = every referenced path is either shipped or explicitly accepted; 1 = a new phantom.
set -uo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT" || exit 1

if [ ! -d .git ] || [ ! -f package.json ]; then
  echo "SKIP  package-coverage (not a source checkout)"
  exit 0
fi

# ── Accepted-absent, with the reason each one is NOT a defect ────────────────────────────────
# Adding a line here is a decision, not a silencer: each entry states why shipping it would be
# wrong. If you cannot write that sentence, the file probably belongs in files[].
#
#   .claude/registry/LOCAL_SKILL_REGISTRY.md — per-environment, generated by the registry scan.
#       Its consumers probe it with `ls … 2>/dev/null` and handle absence; shipping one machine's
#       registry would hand every consumer a false map of skills they do not have.
#   .claude/regression/probes.md            — per-environment prompt-regression baselines. The
#       skill explicitly prints NO_CUSTOM_PROBES when absent. Shipping FH's baselines would make
#       a consumer's regression run compare against someone else's harness.
#   scripts/sync-to-be.sh                   — operator-private companion-store sync. Never ships.
#       (The reference that flags it is a TEST FIXTURE in prepush_guard_check.sh which *creates*
#        a file of that name to exercise the LOW allowlist — not a pointer to this file at all.)
#   scripts/sync_guard_check.sh             — anchor for that same operator-private mirror sync;
#       no shipped hook invokes it.
ACCEPTED_ABSENT=(
  ".claude/registry/LOCAL_SKILL_REGISTRY.md"
  ".claude/regression/probes.md"
  "scripts/sync-to-be.sh"
  "scripts/sync_guard_check.sh"
)

out=$(python3 - "${ACCEPTED_ABSENT[@]}" <<'PY'
import re, os, json, sys
accepted = set(sys.argv[1:])
files = json.load(open('package.json'))['files']

def covered(p):
    return any(p == f or p.startswith(f.rstrip('/') + '/') for f in files)

shipped = []
for f in files:
    if os.path.isfile(f):
        shipped.append(f)
    elif os.path.isdir(f):
        for root, _, names in os.walk(f):
            shipped.extend(os.path.join(root, n) for n in names)

# Only text surfaces can carry a reference a human or agent would follow.
shipped = [s for s in shipped if s.endswith(('.md', '.sh', '.js', '.json', '.yaml', '.yml'))]

pat = re.compile(
    r'(?<![\w/.-])((?:scripts|templates|bin|docs|knowledge|plugins|\.claude)'
    r'/[A-Za-z0-9_./-]+\.(?:sh|py|js|md|yaml|yml|json|defaults))'
)

phantom = {}
for s in shipped:
    try:
        text = open(s, encoding='utf-8', errors='ignore').read()
    except OSError:
        continue
    for m in set(pat.findall(text)):
        # Only a path that REALLY EXISTS here but is left out of the tarball is this defect.
        # A path that exists nowhere is the ordinary phantom-reference class the ref-path
        # check above already owns; a path outside files[] that is also absent is nothing.
        if os.path.exists(m) and not covered(m) and m not in accepted:
            phantom.setdefault(m, set()).add(s)

# Impossible-zero guard: this repo always has shipped docs. Zero scanned means the extractor
# broke — report that as a failure rather than letting a dead check print a pass
# (same rule as count_check.sh and the ref-path extractor).
if not shipped:
    print("EXTRACTOR_BROKE")
    raise SystemExit(2)

for p, srcs in sorted(phantom.items(), key=lambda kv: (-len(kv[1]), kv[0])):
    print(f"{p}\t{len(srcs)}\t{sorted(srcs)[0]}")
raise SystemExit(1 if phantom else 0)
PY
)
rc=$?

if [ "$rc" -eq 2 ] || [ "$out" = "EXTRACTOR_BROKE" ]; then
  echo "FAIL  package-coverage: extractor scanned 0 shipped docs — the check broke, it did not pass"
  exit 1
fi

if [ "$rc" -ne 0 ]; then
  echo "FAIL  package-coverage: shipped document(s) point at file(s) the package omits:"
  printf '%s\n' "$out" | while IFS=$'\t' read -r path n src; do
    [ -z "$path" ] && continue
    printf '        %s  (named by %s shipped doc(s), e.g. %s)\n' "$path" "$n" "$src"
  done
  echo "      Fix: add the path to package.json files[], OR list it in ACCEPTED_ABSENT here"
  echo "      with a one-sentence reason why shipping it would be wrong."
  exit 1
fi

echo "PASS  package-coverage: every referenced path is shipped or explicitly accepted (${#ACCEPTED_ABSENT[@]} accepted)"
exit 0
