#!/usr/bin/env bash
# package_coverage_check.sh — a shipped document must not point at a file the package omits.
#
# WHY (measured 2026-07-28): the npm tarball shipped CLAUDE.md, README, CATALOG and the knowledge/
# base while omitting much of what they instruct the reader to open — 35 distinct paths existed in
# the repo, were named by a shipped document, and were absent from the tarball. `CLAUDE.md` told
# consumers to run `templates/predelete_check.sh` before a destructive op; that file did not ship.
# A gate you are told to run and cannot run is worse than one you were never told about.
#
# This is the ANTI-REGROWTH instrument for that class. Closing the 35 once is worth little: the set
# regrows every time a doc gains a reference or files[] gains an entry. So the check is mechanical
# and the exceptions are ENUMERATED, never implicit.
#
# SOURCE-TREE ONLY. Inside an installed package the un-shipped files are legitimately absent and
# package.json's files[] may not even be present in a comparable form, so the check self-skips.
#
# Usage:  bash scripts/package_coverage_check.sh
# Exit:   0 = every referenced path is either shipped or explicitly accepted; 1 = a new phantom.
set -uo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT" || exit 1

# ── Accepted-absent, with the reason each one is NOT a defect ────────────────────────────────
# Adding a line here is a decision, not a silencer: each entry states why shipping it would be
# wrong. If you cannot write that sentence, the file probably belongs in files[].
#
#   .claude/registry/LOCAL_SKILL_REGISTRY.md — per-environment, generated by the registry scan.
#       Its consumers probe it with `ls … 2>/dev/null` and handle absence; shipping one machine's
#       registry would hand every consumer a false map of skills they do not have.
#   .claude/regression/probes.md            — per-environment prompt-regression baselines. The
#       skill explicitly prints NO_CUSTOM_PROBES when absent. Shipping FH's baselines would make
#       a consumer's regression run compare against someone else's harness.
#   scripts/sync-to-be.sh                   — operator-private companion-store sync. Never ships.
#       (The reference that flags it is a TEST FIXTURE in prepush_guard_check.sh which *creates*
#        a file of that name to exercise the LOW allowlist — not a pointer to this file at all.)
#   scripts/sync_guard_check.sh             — anchor for that same operator-private mirror sync;
#       no shipped hook invokes it.
ACCEPTED_ABSENT=(
  ".claude/registry/LOCAL_SKILL_REGISTRY.md"
  # An INSTALL DESTINATION the user creates (`cp templates/local_fh_context.md
  # .claude/rules/local_fh_context.md`), not a file FH ships. Shipping it would overwrite the
  # user's own cross-context wiring — the template it is copied FROM is what ships.
  ".claude/rules/local_fh_context.md"
  ".claude/regression/probes.md"
  # Its sibling, and absent for the same reason one layer up: this file records which sections of
  # THIS repo's resident CLAUDE.md were measured load-bearing. A consumer's CLAUDE.md is their
  # own text, so our verdicts are not merely useless to them — cited from a shipped doc they would
  # read as claims about THEIR file. The shipped docs name it as the place verdicts live in the
  # harness repo, which is a pointer for contributors, not a promise of a shipped artifact.
  ".claude/regression/ablation_verdicts.md"
  "scripts/sync-to-be.sh"
  "scripts/sync_guard_check.sh"
  # Return path (companion store → hub) and its anchor. Same reason as the forward path above: the
  # transport only means anything on a machine that HAS the operator's companion store, and shipping
  # it would hand every consumer a script that resolves `$BE` to nothing. selfcheck references the
  # anchor but guards on the subject's presence, so package mode SKIPs rather than falling through.
  "scripts/sync-from-be.sh"
  "scripts/sync_from_be_lanes.sh"
  # Its only input is `.claude/regression/probes.md`, itself ACCEPTED_ABSENT above (a consumer's
  # regression run must not compare against this harness's probe set). Shipping the reader without
  # its corpus would put a script in the package that can only ever report "instrument error".
  "scripts/probe_scope_check.sh"
  # The known-pair precondition for `probe_scope_check.sh`'s ablation procedure. Absent for the same
  # reason as its subject — the procedure ablates THIS repo's resident CLAUDE.md, so a consumer has
  # nothing to point it at — plus one of its own: every run spends API calls against the consumer's
  # account. Shipping a script whose only effect on a consumer's machine is a bill is worse than
  # omitting it.
  "scripts/ablation_calibrate.sh"
  # Its anchor. Absent for exactly one reason — its SUBJECT is absent — and that pairing is the whole
  # rule: shipping an anchor whose subject is not in the package is the defect that put a red
  # selfcheck in front of every 1.4.85/1.4.86 consumer. selfcheck's block SKIPs when the subject is
  # missing, so the package stays green without pretending the lanes ran.
  "scripts/test_ablation_calibrate_lanes.sh"
  # Anchor for probe_scope_check.sh, which is ACCEPTED_ABSENT above for want of its corpus. Same
  # pairing rule: an anchor whose subject does not ship must not ship either, or the consumer's
  # selfcheck goes red on a subject they do not have.
  "scripts/test_probe_scope_lanes.sh"
  # Measures what the LIVE `claude` CLI does with several SessionStart hooks on one matcher —
  # so every run needs the CLI, auth, and spends tokens on the consumer's account. This anchor DOES
  # get a live run attempt when its subject ships and the file itself is present (selfcheck reports
  # NOT EXERCISED, exit 2, when that run finds no CLI). This entry covers the OTHER case: the anchor
  # FILE ITSELF is not shipped, so selfcheck never gets far enough to attempt the run at all — that
  # case renders SKIP, not NOT EXERCISED (the two are for missing-file vs. present-file-no-CLI,
  # not interchangeable; corrected 2026-08-12, cross-family review — the two exit paths were
  # conflated in an earlier revision of this comment).
  "scripts/test_sessionstart_multihook_lanes.sh"
  # The launchd-driven daily cadence runner. Two independent reasons it must not ship: it is half of
  # a pair whose other half is a machine-local plist (`scripts/com.forge-harness.frontier-digest.plist`),
  # and every run spends `claude` CLI calls on the consumer's account — the same "its only effect on
  # a consumer's machine is a bill" rule as `ablation_calibrate.sh` above. It also writes into
  # `tracks/`, which does not ship. The frontier-digest SKILL names it as the *hub's* production
  # runner (labelled hub-local at the reference), which is a pointer for contributors, not a promise
  # of a shipped artifact — the skill's own save path works without it.
  "scripts/frontier_digest_daily.sh"
)

# `--list-accepted`: print the ACCEPTED_ABSENT paths, one per line, and exit — no git/package.json
# dependency, deliberately callable from a context this script's own coverage scan cannot run in
# (package mode, or a vendored tree with `.git` present but no `package.json` at this root). This is
# the single declared source of "known-legitimately-unshipped" for OTHER checks to consult instead of
# re-deriving the same judgment from an environment predicate (`.git` presence, directory existence)
# that answers a different question and can diverge from this list's actual coverage. Added
# 2026-08-12 (reship axis, cross-family review of card §🔱⑮ G/D) after selfcheck.sh's ref-path block
# was found re-deriving "is this legitimately absent" from `[ -e .git ]` — which reproduces the
# original bug in any git-tracked tree that vendors this package (a monorepo committing
# node_modules, or a consumer who runs `git init` after install): `.git` exists there, so the old
# predicate ran the check, found these exact paths missing, and FAILed — the same false-FAIL this
# array already declares correct to omit.
if [ "${1:-}" = "--list-accepted" ]; then
  printf '%s\n' "${ACCEPTED_ABSENT[@]}"
  exit 0
fi

# Source-checkout test uses `-e`, not `-d`. In a git WORKTREE `.git` is a FILE (a gitdir pointer),
# so the old `-d` test read every worktree as "installed package" and skipped the check entirely —
# silently, with exit 0. Measured 2026-07-31: a worktree created specifically to approximate CI
# reported PASS while this check had not run at all, i.e. the instrument used to justify wiring CI
# was itself fail-open on the surface it was standing in. `-e` covers both the ordinary checkout
# (dir) and the worktree (file); genuine package mode has no `.git` of either kind, so it still
# skips. Anchored by scripts/test_package_coverage_lanes.sh.
if [ ! -e .git ]; then
  echo "SKIP  package-coverage (not a source checkout)"
  exit 0
fi
# PREDICATE SPLIT (cross-family review, 2026-07-31). These were one condition, and folding them
# together meant `.git` present + manifest missing returned SKIP + exit 0 — "we are in a checkout
# and cannot read what ships" reported as "nothing to check here". Absence of the input is not
# absence of the defect; `not found != 0` (CLAUDE.md §Instrument-Calibration). Only the no-.git
# case is a legitimate skip (an installed package, where the un-shipped files are correctly gone).
if [ ! -f package.json ]; then
  echo "FAIL  package-coverage: source checkout with no package.json — the shipped file list is"
  echo "      unreadable, so coverage is UNMEASURED, not clean"
  exit 1
fi

out=$(python3 - "${ACCEPTED_ABSENT[@]}" <<'PY'
import re, os, json, sys
accepted = set(sys.argv[1:])
files = json.load(open('package.json'))['files']

def covered(p):
    return any(p == f or p.startswith(f.rstrip('/') + '/') for f in files)

shipped = []
for f in files:
    if os.path.isfile(f):
        shipped.append(f)
    elif os.path.isdir(f):
        for root, _, names in os.walk(f):
            shipped.extend(os.path.join(root, n) for n in names)

# Only text surfaces can carry a reference a human or agent would follow.
shipped = [s for s in shipped if s.endswith(('.md', '.sh', '.js', '.json', '.yaml', '.yml'))]

pat = re.compile(
    r'(?<![\w/.-])((?:scripts|templates|bin|docs|knowledge|plugins|\.claude)'
    r'/[A-Za-z0-9_./-]+\.(?:sh|py|js|md|yaml|yml|json|defaults))'
)

phantom = {}
exercised = set()   # accepted entries a shipped doc ACTUALLY still points at
for s in shipped:
    try:
        text = open(s, encoding='utf-8', errors='ignore').read()
    except OSError:
        continue
    for m in set(pat.findall(text)):
        # Only a path that REALLY EXISTS here but is left out of the tarball is this defect.
        # A path that exists nowhere is the ordinary phantom-reference class the ref-path
        # check above already owns; a path outside files[] that is also absent is nothing.
        # EXISTENCE, not tracked-ness. A 2026-07-30 revision narrowed this to `git ls-files`
        # to silence what looked like a machine-local false positive; measurement showed that was a
        # WEAKENING — an existing-but-untracked path named by a shipped doc is exactly the defect
        # (the npm user cannot have that file), and selfcheck's ref-path check SKIPs gitignored
        # paths, so nothing else owns it. Reverted.
        #
        # WIDENING IS DEFERRED, AND THE REASON IS NOT A MEASUREMENT. Dropping `exists` entirely
        # (flag every referenced ∧ ¬covered path) is arguably the correct predicate, but it cannot
        # be evaluated while the extractor below is known-broken: its `(sh|py|js|md|json|…)`
        # alternation puts `js` before `json`, so `settings.json` is captured as `settings.js`.
        # A first pass at this comment cited a count of artifacts as evidence that `exists` is
        # load-bearing — that count came FROM the broken extractor, i.e. an instrument was used to
        # justify keeping a predicate before the instrument itself was validated (the circularity
        # CLAUDE.md §Instrument-Calibration exists to forbid; a cross-family review caught it, and
        # an independent extractor produced materially different numbers).
        # HONEST STATE: fix the `js|json` alternation first, re-measure, then decide. Until then
        # this check's true coverage is UNQUANTIFIED — treat a PASS as "no defect of the narrow
        # exists-and-uncovered kind", not as "every shipped reference is sound".
        if os.path.exists(m) and not covered(m):
            if m in accepted:
                exercised.add(m)
            else:
                phantom.setdefault(m, set()).add(s)

# Impossible-zero guard: this repo always has shipped docs. Zero scanned means the extractor
# broke — report that as a failure rather than letting a dead check print a pass
# (same rule as count_check.sh and the ref-path extractor).
if not shipped:
    print("EXTRACTOR_BROKE")
    raise SystemExit(2)

for p, srcs in sorted(phantom.items(), key=lambda kv: (-len(kv[1]), kv[0])):
    print(f"{p}\t{len(srcs)}\t{sorted(srcs)[0]}")

# An exception nobody exercises is a SILENCER waiting for a future real case to land on it.
# Report the unexercised ones so the list stays a set of decisions, not accumulated residue.
for a in sorted(accepted - exercised):
    print(f"STALE\t{a}")
raise SystemExit(1 if phantom else 0)
PY
)
rc=$?

if [ "$rc" -eq 2 ] || [ "$out" = "EXTRACTOR_BROKE" ]; then
  echo "FAIL  package-coverage: extractor scanned 0 shipped docs — the check broke, it did not pass"
  exit 1
fi

STALE_LIST=$(printf '%s\n' "$out" | grep '^STALE	' | cut -f2- || true)
STALE_N=$(printf '%s' "$STALE_LIST" | grep -c . || true)
EXERCISED_N=$(( ${#ACCEPTED_ABSENT[@]} - ${STALE_N:-0} ))

if [ "$rc" -ne 0 ]; then
  echo "FAIL  package-coverage: shipped document(s) point at file(s) the package omits:"
  printf '%s\n' "$out" | grep -v '^STALE	' | while IFS=$'\t' read -r path n src; do
    [ -z "$path" ] && continue
    printf '        %s  (named by %s shipped doc(s), e.g. %s)\n' "$path" "$n" "$src"
  done
  echo "      Fix: add the path to package.json files[], OR list it in ACCEPTED_ABSENT here"
  echo "      with a one-sentence reason why shipping it would be wrong."
  exit 1
fi

# Advisory only — a stale exception is hygiene, not a shipped-doc defect, so it must not
# convert a clean package into a red gate (that trains the runner to ignore the check).
if [ "${STALE_N:-0}" -gt 0 ]; then
  echo "⚠️  package-coverage: ${STALE_N} ACCEPTED_ABSENT entry(ies) no longer exercised — remove, or a"
  echo "    future real omission can land on the stale exception and be silenced:"
  printf '%s\n' "$STALE_LIST" | sed 's/^/        /'
fi

echo "PASS  package-coverage: every referenced path is shipped or explicitly accepted (${#ACCEPTED_ABSENT[@]} accepted, ${EXERCISED_N} exercised)"
exit 0
